BASE_PATH = "docs/inputs"
OUTPUT_PATH = "docs/outputs"
LISTA_DIRECCIONES = [
        BASE_PATH + "/admitidos",
        BASE_PATH + "/graduados",
        BASE_PATH + "/inscritos",
        BASE_PATH + "/matriculados",
        BASE_PATH + "/matriculadosPrimerCurso"
    ]

STR_CODIGO_SNIES = "CÓDIGO SNIES DEL PROGRAMA"
STR_PROGRAMA_ACADEMICO = "PROGRAMA ACADÉMICO"
STR_METODOLOGIA = "METODOLOGÍA"
STR_NOMBRE_IES = "INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)"
STR_TIPO_IES = "PRINCIPAL O SECCIONAL"
STR_DEPARTAMENTO ="DEPARTAMENTO DE DOMICILIO DE LA IES"
STR_MUNICIPIO = "MUNICIPIO DE DOMICILIO DE LA IES"
STR_NIVEL_FORMACION = "NIVEL DE FORMACIÓN"
STR_SEMESTRE = "SEMESTRE"
STR_ADMITIDOS = "ADMITIDOS"
STR_GRADUADOS = "GRADUADOS"
STR_INSCRITOS = "INSCRITOS"
STR_MATRICULADOS = "MATRICULADOS"
STR_PRIMER_CURSO = "PRIMER CURSO"

ARCHIVOS_NECESARIOS = {
        LISTA_DIRECCIONES[0] : "admitidos",
        LISTA_DIRECCIONES[1] : "graduados",
        LISTA_DIRECCIONES[2] : "inscritos",
        LISTA_DIRECCIONES[3] : "matriculados",
        LISTA_DIRECCIONES[4] : "matriculadosPrimerCurso"
}